[book]
authors = ["toilari"]
language = "en"
multilingual = false
src = "src"
title = "Step by step towards Insanity"

[output.html]
theme = "src/theme"
mathjax-support = true
google-analytics = "UA-159929183-1"
